name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
            cd JD-analysis-wechat-serverside || echo 'cd fail'
            pwd
            #git fetch --all && git reset --hard origin/master && mvn clean && mvn install -Dmaven.test.skip=true && cd target && nohup java -jar wechat-serverside-0.0.1-SNAPSHOT.jar &
